# Generated by Django 3.2.6 on 2022-04-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_auto_20220416_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='is_active',
            field=models.BooleanField(null=True, verbose_name='حذف شده/نشده'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='title',
            field=models.CharField(db_index=True, max_length=300, verbose_name='نام برند'),
        ),
    ]
