# Generated by Django 3.2.6 on 2022-04-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_auto_20220417_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrand',
            name='is_active',
            field=models.BooleanField(null=True, verbose_name='فعال/غیر فعال'),
        ),
    ]
