# Generated by Django 3.2.13 on 2022-08-20 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_product_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_gallery_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(height_field='75', upload_to='images/product_gallery', verbose_name='عکص محصول', width_field='75')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'تصاویر گالری',
            },
        ),
    ]
