# Generated by Django 3.2.13 on 2022-08-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_product_gallery_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_gallery_images',
            name='images',
        ),
        migrations.AddField(
            model_name='product_gallery_images',
            name='image',
            field=models.ImageField(default=1, upload_to='images/product_gallery', verbose_name='عکص محصول'),
            preserve_default=False,
        ),
    ]
