# Generated by Django 3.2.13 on 2022-09-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_detail',
            options={'verbose_name': 'جزییات سبد خرید', 'verbose_name_plural': 'لیست جزییات سبدهای خرید'},
        ),
    ]
