# Generated by Django 3.2.13 on 2022-05-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_category',
            name='url_title',
            field=models.CharField(max_length=200, unique=True, verbose_name='عنوان لینک'),
        ),
    ]
