# Generated by Django 3.2.13 on 2022-08-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_auto_20220523_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adress',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره همراه'),
        ),
    ]
